from pathlib import Path

OPENBASE_BASE_DIR = Path.home() / ".openbase"
# Backend CLI binaries (codex, claude) installed on demand by setup.
OPENBASE_BIN_DIR = OPENBASE_BASE_DIR / "bin"
# Standalone runtime package releases activated by the desktop app/install.sh.
STANDALONE_PACKAGES_DIR = OPENBASE_BASE_DIR / "packages" / "standalone"
STANDALONE_RELEASES_DIR = STANDALONE_PACKAGES_DIR / "releases"
STANDALONE_CURRENT_DIR = STANDALONE_PACKAGES_DIR / "current"
OPENBASE_SOUNDS_DIR = OPENBASE_BASE_DIR / "sounds"
OPENBASE_INSTRUCTIONS_DIR = OPENBASE_BASE_DIR / "instructions"
CODEX_HOME_DIR = OPENBASE_BASE_DIR / "codex_home"
CODEX_AGENTS_MD_PATH = CODEX_HOME_DIR / "AGENTS.md"
NORMAL_CODEX_HOME_DIR = Path.home() / ".codex"
NORMAL_CODEX_AGENTS_MD_PATH = NORMAL_CODEX_HOME_DIR / "AGENTS.md"
NORMAL_CODEX_CONFIG_PATH = NORMAL_CODEX_HOME_DIR / "config.toml"
NORMAL_CLAUDE_CONFIG_DIR = Path.home() / ".claude"
NORMAL_CLAUDE_SETTINGS_PATH = NORMAL_CLAUDE_CONFIG_DIR / "settings.json"
NORMAL_CLAUDE_STATE_PATH = Path.home() / ".claude.json"
OPENBASE_CLAUDE_CONFIG_DIR = OPENBASE_BASE_DIR / "claude_config"
OPENBASE_CLAUDE_JSON_PATH = OPENBASE_CLAUDE_CONFIG_DIR / ".claude.json"
OPENBASE_CLAUDE_MD_PATH = OPENBASE_CLAUDE_CONFIG_DIR / "CLAUDE.md"
OPENBASE_CLAUDE_SETTINGS_PATH = OPENBASE_CLAUDE_CONFIG_DIR / "settings.json"
OPENBASE_DIRECT_LIVEKIT_INSTRUCTIONS_PATH = (
    OPENBASE_INSTRUCTIONS_DIR / "VOICE_INSTRUCTIONS.md"
)
OPENBASE_DISPATCHER_INSTRUCTIONS_PATH = (
    OPENBASE_INSTRUCTIONS_DIR / "DISPATCHER_INSTRUCTIONS.md"
)
OPENBASE_SUPER_AGENT_INSTRUCTIONS_PATH = (
    OPENBASE_INSTRUCTIONS_DIR / "SUPER_AGENT_INSTRUCTIONS.md"
)
OPENBASE_VOCALBRIDGE_INSTRUCTIONS_PATH = (
    OPENBASE_INSTRUCTIONS_DIR / "VOCALBRIDGE_DISPATCHER_INSTRUCTIONS.md"
)
VOCALBRIDGE_THREAD_STATE_PATH = OPENBASE_BASE_DIR / "vocalbridge-dispatcher.json"
CODEX_DIRECT_LIVEKIT_INSTRUCTIONS_PATH = OPENBASE_DIRECT_LIVEKIT_INSTRUCTIONS_PATH
CODEX_DISPATCHER_INSTRUCTIONS_PATH = OPENBASE_DISPATCHER_INSTRUCTIONS_PATH
OPENBASE_DISPATCHER_CONFIG_PATH = OPENBASE_BASE_DIR / "dispatcher-config.json"
CODEX_DISPATCHER_CONFIG_PATH = OPENBASE_DISPATCHER_CONFIG_PATH
CODEX_SUPER_AGENT_INSTRUCTIONS_PATH = OPENBASE_SUPER_AGENT_INSTRUCTIONS_PATH
INSTALLATION_JSON_PATH = OPENBASE_BASE_DIR / "installation.json"
DEFAULT_ENV_FILE_PATH = OPENBASE_BASE_DIR / ".env"
DEFAULT_LOG_DIR = OPENBASE_BASE_DIR / "logs"
LAUNCHD_WRAPPER_DIR = OPENBASE_BASE_DIR / "launchd"
PLIST_DIR = Path.home() / "Library" / "LaunchAgents"
SYSTEMD_UNIT_DIR = Path.home() / ".config" / "systemd" / "user"
LAUNCHD_DOMAIN = "com.openbase.coder"
AUTH_JSON_PATH = OPENBASE_BASE_DIR / "auth.json"
SYNC_CONFIG_PATH = OPENBASE_BASE_DIR / "sync-config.json"
CODE_SYNC_DIR = OPENBASE_BASE_DIR / "code-sync"
CODE_SYNC_CONFLICTS_PATH = CODE_SYNC_DIR / "conflicts.json"
SYNC_VERSIONS_DIR = OPENBASE_BASE_DIR / "sync-versions"
MACHINE_TOKEN_JSON_PATH = OPENBASE_BASE_DIR / "machine-token.json"
CONSOLE_SETTINGS_JSON_PATH = OPENBASE_BASE_DIR / "console-settings.json"
ONBOARDING_JSON_PATH = OPENBASE_BASE_DIR / "onboarding.json"
DESKTOP_CONTROL_JSON_PATH = OPENBASE_BASE_DIR / "desktop-control.json"

PLUGIN_BASE_DIR = OPENBASE_BASE_DIR / "plugins"
# Stable site dir for plugin Python packages in standalone installs; lives
# outside the versioned runtime package so upgrades don't drop plugins.
PLUGIN_SITE_DIR = PLUGIN_BASE_DIR / "site"
PLUGIN_REGISTRY_PATH = PLUGIN_BASE_DIR / "plugins.json"
PLUGIN_REQUIREMENTS_PATH = PLUGIN_BASE_DIR / "plugin_requirements.txt"
PLUGIN_SOURCES_DIR = PLUGIN_BASE_DIR / "sources"
PLUGIN_CONSOLE_REGISTRY_PATH = PLUGIN_BASE_DIR / "console" / "registry.json"
PLUGIN_CONSOLE_ASSETS_DIR = PLUGIN_BASE_DIR / "console-assets"
PLUGIN_SKILLS_OWNERSHIP_PATH = PLUGIN_BASE_DIR / "skills_ownership.json"
